openapi: 3.2.0
info:
  title: NextGen Catalog Metadata API
  version: 0.2.0
  description: This is the NextGen Catalog API application made with Express and documented with Swagger.
servers:
- url: https://catalog.archives.gov/api/v2/
tags:
- name: Metadata
paths:
  /metadata/naid-availability/naid/{naId}:
    get:
      summary: Get digital object IDs by matching Ancestry metadata in partner-metadata index
      description: Returns a list of digital object IDs that match the given naid in the partner-metadata index.
      tags:
      - Metadata
      parameters:
      - name: naId
        in: path
        required: true
        schema:
          type: string
        description: The naid to search for in the partner-metadata index.
      responses:
        '200':
          description: A list of digital object IDs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ids:
                    type: array
                    items:
                      type: string
                    description: List of matching digital object IDs.
        '400':
          description: Bad Request. Invalid naid provided.
        '404':
          description: No matching records found.
        '500':
          description: Internal server error.
      operationId: getMetadataNaidAvailabilityNaidByNaId
      x-operation-id-source: derived
