openapi: 3.2.0
info:
  title: NextGen Catalog Statistics API
  version: 0.2.0
  description: This is the NextGen Catalog API application made with Express and documented with Swagger.
servers:
- url: https://catalog.archives.gov/api/v2/
tags:
- name: Statistics
paths:
  /records/stats:
    get:
      summary: Retrieve statistics related to user contributions
      description: Fetches aggregated statistics for different contribution types (e.g., comments, tags, transcriptions) across various record types (e.g., authorityRecords, digitalObjects, descriptions). The results include a breakdown by contribution type and grand totals.
      tags:
      - Statistics
      responses:
        '200':
          description: Successfully retrieved contribution statistics.
          content:
            application/json:
              schema:
                type: object
                properties:
                  digitalObjects:
                    $ref: '#/components/schemas/ContributionRecord'
                  descriptions:
                    $ref: '#/components/schemas/ContributionRecord'
                  authorityRecords:
                    $ref: '#/components/schemas/ContributionRecord'
                  metaData:
                    $ref: '#/components/schemas/MetaData'
        '500':
          description: Internal server error
      operationId: getRecordsStats
      x-operation-id-source: derived
